### ISSUE TITLE
Adds continuous deployment to the "Latest Docker Image" workflow 

### ISSUE THREAD

**Issue by carloshellin** [propagamap/openelevationservice#11]
1. Enable the webhook of this container at https://deploy.propamap.cc.uah.es/
2. Create a secret in this repo called WEBHOOK_URL (if you don't have permissions, reply in this issue with the URL and I'll create it)
3. Add the deploy job after build in the "Latest Docker Image CI" worflow. Use this code as an example:
```
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Invoke deployment hook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}?tag=latest
          insecure: true
```
4. Check that it works. Every time a push is made to the main, the image of a container should be created and that image should automatically be deployed in the container at https://deploy.propamap.cc.uah.es/.
